# Fake data testing of phenology budburst experiment at individual tree level - for stan user group.
library(rstan)
library(ggplot2)
library(shinystan)

setwd("~/Documents/git/treetraits/analyses")

rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

# get latest .Rdata file; this is generated by FakeBudburst_Generate_ind2.R 
load("Fake_Budburst_ind2.RData") # dataframe 'fake' is 800 rows, 10 ind x 20 sp x 4 treatments

# Make a lookup vector for which species each individual tree belongs to
splookup <- unique(fake[c("ind","sp")])[,"sp"] #200 long = 10 ind x 20 sp 

# To Stan
datalist.f <- with(fake, 
              list(y = bb, # budburst as respose 
                   sp = as.numeric(sp), 
                   ind = as.numeric(ind),
                   warm = as.numeric(warm), 
                   photo = as.numeric(photo), 
                   N = nrow(fake), 
                   splookup = splookup,
                   n_sp = length(unique(sp)),
                   n_ind = length(unique(ind))
                   )
)

doym.f <- stan('stan/lday_ind2.stan', data = datalist.f, 
                 iter = 5005,
               control = list(adapt_delta = 0.9,
                              max_treedepth = 15)) 

sf <- summary(doym.f)$summary

ssm.f <- as.shinystan(doym.f)
launch_shinystan(ssm.f) 

# savestan("Fake Small for GG") # using function to save stan objects for later

# Looking at distribution of intercept values -- too high! Should be in range of 35
plot(density(sf[grep("^a_sp\\[", rownames(sf)),'mean']),
     main = "Intercepts", col = 'darkred')
lines(density(sf[grep("^a_sp_ind\\[", rownames(sf)),'mean']),
     col = 'midnightblue')
legend('topleft', bty = 'n', col = c('darkred','midnightblue'), legend = c('Species level','Individual level'), lty = 1)

# These look fine
plot(density(sf[grep("^b_warm_sp\\[", rownames(sf)),'mean']),
     main = "Species level warming effects")

plot(density(sf[grep("^b_warm_sp_ind\\[", rownames(sf)),'mean']),
     main = "Individual level warming effects")

###### Posterior predictive checks
# pull out coefficients at each level. Use same process as for generating fake data

nsp = length(unique(fake$sp)) # 20 species
ntreat = with(fake, length(unique(paste(warm, photo)))) # 4 treatments
# all(tapply(fake$ind, fake$sp, length) == 40) # make sure all are the same
nind = mean(tapply(fake$ind, fake$sp, length) / ntreat)  #10

nwarm = length(unique(fake$warm)) # 2 temperature treatments
nphoto = length(unique(fake$photo)) # 2 photoperiod treatments

rep = 1 # only 1 cutting from an individual within each combination of treatments. 

(ntot = nwarm*nphoto) # 4 rows. But will be looping over individuals and species below

# Build up the data frame
warm = gl(nwarm, rep, length = ntot)
photo = gl(nphoto, rep*nwarm, length = ntot)

treatcombo = paste(warm, photo, sep = "_")

(d <- data.frame(warm, photo, treatcombo))

# Extracting fitted values from the stan fit object
warmdiff = sf[grep("^b_warm_0", rownames(sf)),'mean']
photodiff = sf[grep("^b_photo_0", rownames(sf)),'mean']

######## SD for each treatment
warmdiff.sd = sf[grep("^b_warm_0", rownames(sf)),'sd']  
photodiff.sd = sf[grep("^b_photo_0", rownames(sf)),'sd'] 

mm <- model.matrix(~(warm+photo), data.frame(warm, photo))

############ !
spint <- sf[grep("^a_sp\\[", rownames(sf)),'mean'] # Was centered on 35 in fake data, why now 65??

poster <- vector() # to hold the posterior predictive checks

for(i in 1:nsp){ # loop over species, as these are the random effect modeled. 
  # Within species, have a loop for individuals
  
  indx <- which(splookup == i)
  
  coeff <- data.frame(
      sf[rownames(sf) %in% paste("a_sp_ind[", indx, "]", sep = ""),'mean'],
      sf[rownames(sf) %in% paste("b_warm_sp_ind[", indx, "]", sep = ""),'mean'],
      sf[rownames(sf) %in% paste("b_photo_sp_ind[", indx, "]", sep = ""),'mean']
      )
    
    for(j in 1:nind){ # simulate data for each individual, using these coefficients
      
      bb <- rnorm(n = length(warm), mean = mm %*% as.numeric(coeff[j,]), sd = 0.1)
    
      posterx <- data.frame(bb, sp = i, ind = paste(i, j, sep="_"),
                        warm, photo)
    
    poster <- rbind(poster, posterx)  
  }
}

plot(fake$bb, poster$bb,
     xlab = "Simulated data",
     ylab = "Posterior predictive check",
     xlim = c(-10, 90),
     ylim = c(-10, 90),
     pch = 16,
     col = alpha('midnightblue', 0.2)
     )
abline(a=0, b=1, lty=3)


